### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/geogebra#2]
This Package will be removed in 7 days from KCP.

Reason: **Unmaintained/Outdated** and also **Broken**
`==> ERROR: Failure while downloading http://download.geogebra.org/installers/4.4/GeoGebra-Linux-Installer-4.4.42.0.tar.gz`

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145)

**Comment by forostm** [comment]
Updated
